### ISSUE TITLE
Question: find out who the current user is 

### ISSUE THREAD

**Issue by sindbach** [paviliondev/discourse-landing-pages#10]
Hi @angusmcleod, 

A question about [partials and helpers](https://thepavilion.io/t/partials-and-helpers/4097). 
As I understand it now, there is no helpers available to find out who the current user is i.e. the user that is viewing the landing page.  

Is this because of a technical limitation of the helpers  ? (i.e. The plugin currently does not have a way to read the user from cookie session id, or internal Discourse passed down information)

Or is this possible but just have not been exposed yet ? 
(i.e. the plugin is able to restrict viewing based on groups, so perhaps there is an internal workings already that identify who the user is)

Regards, 
Wan.

**Comment by sindbach** [comment]
I think I have figured this out by looking at another plugin. 
Within a landing page body i.e. `body.html.erb` you can use `current_user` variable. If a user is logged in, this should be available and shown as the current user object. 

Thank you.

**Comment by angusmcleod** [comment]
@sindbach Sorry I didn't get back to you on this, but yes ``current_user`` is what you need :+1:
