### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by cabidop** [paviliondev/discourse-landing-pages#13]
The main and global sections of the plugin and the README of this repository contain a few documentation links (https://thepavilion.io/c/knowledge/discourse/landing-pages/204, https://thepavilion.io/t/4094 and https://thepavilion.io/t/4098 as far as I could find) that seem to be pointing to contents of a previous version of the Pavilion website/forum that are currently unavailable.

@angusmcleod do you still have a copy of this documentation? If that is the case, it would be a good idea to publish them as wiki pages here.

**Comment by angusmcleod** [comment]
@cabidop I've had a look and unfortunately we don't have the documentation any more.
