### ISSUE TITLE
Is it possible to keep top Discourse menu on landing page?

### ISSUE THREAD

**Issue by psychedel** [paviliondev/discourse-landing-pages#2]
It's probably too early, but maybe I've missed how it can be done with theme selection? 
If it's too long to answer - don't worry, I will try to figure it out.
Thanks!

**Comment by angusmcleod** [comment]
Hey :) This pugin is still in a "pre-release" state, but I'm glad you're using it. The short answer is "not yet". But I'm aware that's going to be a very common request when I "release" this plugin (I make people aware it exists and explain how to use it).

I've added the theme ["header" tag to the layout](https://github.com/paviliondev/discourse-landing-pages/commit/41bac04fade9f052ffeb32b12a419d0dce8d96f7) so you could use that route if you want to, but it's going to be hard doing it that way. Good to have the header tag in there anyway.

If you're willing to work up a PR that does this "properly" I'd be more than happy to help you get it to a mergable state by giving some pointers. The proper approach here is to add a way to selectively include assets from the main Discourse app in the landing pages asset pipeline, i.e. the discourse/discourse header assets should be required [here](https://github.com/paviliondev/discourse-landing-pages/blob/master/assets/javascripts/landing-page-assets.js), only if explicitly required by the page, or global, settings json. 

The reason that's the approach needed is that "recreating" the header in some form is just not sustainable. The Discourse header is quite complicated and changes frequently.

So you would need to

1. Add the page-level and global-level settings
2. Figure out which header assets from the main discourse app are needed. It'll be the ``site-header`` component, plus all of the "header" related widgets, and any libraries or helpers they rely on.
3. Ensure the "live" aspects of the header, i.e. user login state, notifications via the messagebus work properly.
4. Make sure it all works properly in a production env (where asset pipelines are a bit different from dev).

**Comment by 4ong** [comment]
Thanks! I'm experimenting with this and will return to you when/if I will get working results.
Thanks again for the good start point!

**Comment by angusmcleod** [comment]
Great! Let me know if you get stuck.
