### ISSUE TITLE
Clicking on the export button for a local page throws a JS error and fails

### ISSUE THREAD

**Issue by rsmithlal** [paviliondev/discourse-landing-pages#4]
Hi folks,

I'm trying to export a local page so I can commit it to the pages repo that I have set up. However, whenever I click the export button nothing happens, and a JS error is logged to the console.

I can contribute a PR for this if someone is willing to give me a hand and point me in the right direction. I haven't dug into Discourse dev yet, but I have an env set up and need to get my hands dirty =) I want to build my own plugin one day and I need to learn how to work with the platform.

Discourse 2.8.0 beta2
Latest commit of the Landing Pages plugin

The message reads

```
> Uncaught TypeError: this.page.exportPage is not a function
    Ember 61
        exportPage
        _join
        join
        d
        Rn
        a
        Rn
        click
        trigger
        n
        _run
        _join
        join
        d
        handleEvent
        a
        handleEvent
        handleEvent
        setupHandler
        dispatch
        handle
        add
        Se
        each
        each
        Se
        on
        initialize
        initialize
        runInstanceInitializers
        each
        walk
        each
        topsort
        _runInitializer
        runInstanceInitializers
        _bootSync
        didBecomeReady
        invoke
        flush
        flush
        _end
        end
        _run
        _join
        join
        d
        bind
        l
        c
        setTimeout handler*a/<
        u
        fireWith
        fire
        u
        fireWith
        ready
        B
        EventListener.handleEvent*
        <anonymous>
        <anonymous>
_discourse-landing-pages-b9fedf4501a883449d41c1c31913d58677108c57d2ba865803d28d3ec18cd328.js:201:18
    Ember 61
```

I'm attaching a screenshot showing the source code that is throwing the error. 

![Screenshot from 2021-07-14 09-24-54](https://user-images.githubusercontent.com/11048570/125618719-557fb9b3-fe4f-413d-9c65-446009401a9f.png)

**Comment by angusmcleod** [comment]
@rsmithlal Hey! Thanks for reporting this, and glad to hear you're keen to develop with Discourse. A PR would be great. The first thing to understand about what's going on here is that Ember, Discourse and the Landing Pages plugin itself follows a standard MVC approach in structuring the Discourse client. 

It looks like what's happened here is that for some reason the ``exportPage`` method on the [page model](https://github.com/paviliondev/discourse-landing-pages/blob/master/assets/javascripts/discourse/models/landing-page.js.es6) is missing. There should be a method in that file that fires an ajax request to [this endpoint](https://github.com/paviliondev/discourse-landing-pages/blob/master/config/routes.rb#L4) in the rails endpoint that the plugin adds to Discourse. Why it's not there now, I'm not sure. The method should look similar to the other methods wrapping ajax calls you see in that file.

If you need help setting up a local development environment the best place to look first is the various topics covering that on meta.discourse.org. I'd be happy to clarify anything about that on meta.discourse.org; you can @mention me here (I'm ``angus``).
